version: '3.7'

services:
  moon:
    container_name: moon
    hostname: moon
    image: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.prod
    command:
      - entrypoints/gunicorn.sh

networks:
  default:
    external: true
    name: dappsheriff
