"""bot_invites

Revision ID: 8a5d18123605
Revises:
Create Date: 2024-06-13 03:07:25.215960

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a5d18123605"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moon_invite_code",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=True, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("referrer_telegram_id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("moon_invite_code_pkey")),
        sa.UniqueConstraint("code", name=op.f("moon_invite_code_code_key")),
        sa.UniqueConstraint(
            "referrer_telegram_id",
            name=op.f("moon_invite_code_referrer_telegram_id_key"),
        ),
    )
    op.create_table(
        "moon_invite",
        sa.Column(
            "id",
            sa.Integer(),
            sa.Identity(always=True, start=1, increment=1),
            nullable=False,
        ),
        sa.Column("invite_id", sa.Integer(), nullable=False),
        sa.Column("referee_telegram_id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invite_id"],
            ["moon_invite_code.id"],
            name=op.f("moon_invite_invite_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("moon_invite_pkey")),
        sa.UniqueConstraint(
            "referee_telegram_id", name=op.f("moon_invite_referee_telegram_id_key")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("moon_invite")
    op.drop_table("moon_invite_code")
    # ### end Alembic commands ###
