name: Run Linters
on:
  push:
    branches:
      - main
      - dev
  pull_request:


jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: 'src alembic'
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
          src: 'src alembic'